#!/usr/bin/env ruby

begin
require "tty"
rescue LoadError
  puts "Install the `tty` gem please"
  exit 1
end

require "bundler/setup"

native_specs = Bundler.definition.resolve.to_a.select { |spec| spec.__materialize__.extensions.any? }

table = TTY::Table.new(
  header: ["Gem Name", "Version"],
  rows: native_specs.sort_by(&:name).map {|spec| [spec.name, spec.version] }
)

puts table.render(:ascii, padding: [0, 1, 0, 1])
