#!/usr/bin/env ruby

require "tty"
require "samovar"

class NativeGems < Samovar::Command
  options do
    option "-g/--group <group>"
  end

  def invoke(argv)
    
  end
end

NativeGems.new(ARGV).invoke
# require "bundler/setup"
#
# native_specs = Bundler.definition.resolve.to_a.select { |spec| spec.__materialize__.extensions.any? }
#
# table = TTY::Table.new(
#   header: ["Gem Name", "Version"],
#   rows: native_specs.sort_by(&:name).map {|spec| [spec.name, spec.version] }
# )
#
# puts table.render(:ascii, padding: [0, 1, 0, 1])
